/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BaserootMarketplaceV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "agents"
      | "buyLicense"
      | "datasets"
      | "getAgent"
      | "getDataset"
      | "getLicense"
      | "hasLicense"
      | "isLicenseActive"
      | "licenseExists"
      | "licenses"
      | "nextLicenseId"
      | "owner"
      | "platformWallet"
      | "registerAgent"
      | "registerDataset"
      | "renounceOwnership"
      | "setPlatformWallet"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRegistered"
      | "DatasetRegistered"
      | "LicensePurchased"
      | "OwnershipTransferred"
      | "PlatformWalletUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "agents", values: [string]): string;
  encodeFunctionData(functionFragment: "buyLicense", values: [string]): string;
  encodeFunctionData(functionFragment: "datasets", values: [string]): string;
  encodeFunctionData(functionFragment: "getAgent", values: [string]): string;
  encodeFunctionData(functionFragment: "getDataset", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getLicense",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasLicense",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isLicenseActive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "licenseExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "licenses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextLicenseId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerDataset",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyLicense", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "datasets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getDataset", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getLicense", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasLicense", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isLicenseActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "licenseExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "licenses", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextLicenseId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerDataset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agentId: string,
    creator: AddressLike,
    price: BigNumberish,
    datasetId: string
  ];
  export type OutputTuple = [
    agentId: string,
    creator: string,
    price: bigint,
    datasetId: string
  ];
  export interface OutputObject {
    agentId: string;
    creator: string;
    price: bigint;
    datasetId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DatasetRegisteredEvent {
  export type InputTuple = [
    datasetId: string,
    owner: AddressLike,
    pricePerUse: BigNumberish
  ];
  export type OutputTuple = [
    datasetId: string,
    owner: string,
    pricePerUse: bigint
  ];
  export interface OutputObject {
    datasetId: string;
    owner: string;
    pricePerUse: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LicensePurchasedEvent {
  export type InputTuple = [
    licenseId: BigNumberish,
    agentId: string,
    buyer: AddressLike,
    amount: BigNumberish,
    creator: AddressLike,
    daoOwner: AddressLike
  ];
  export type OutputTuple = [
    licenseId: bigint,
    agentId: string,
    buyer: string,
    amount: bigint,
    creator: string,
    daoOwner: string
  ];
  export interface OutputObject {
    licenseId: bigint;
    agentId: string;
    buyer: string;
    amount: bigint;
    creator: string;
    daoOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformWalletUpdatedEvent {
  export type InputTuple = [newWallet: AddressLike];
  export type OutputTuple = [newWallet: string];
  export interface OutputObject {
    newWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BaserootMarketplaceV2 extends BaseContract {
  connect(runner?: ContractRunner | null): BaserootMarketplaceV2;
  waitForDeployment(): Promise<this>;

  interface: BaserootMarketplaceV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agents: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, boolean] & {
        creator: string;
        datasetId: string;
        price: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  buyLicense: TypedContractMethod<[_agentId: string], [void], "payable">;

  datasets: TypedContractMethod<
    [arg0: string],
    [
      [string, bigint, boolean] & {
        owner: string;
        pricePerUse: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getAgent: TypedContractMethod<
    [_agentId: string],
    [
      [string, string, bigint, boolean] & {
        creator_: string;
        datasetId_: string;
        price_: bigint;
        exists_: boolean;
      }
    ],
    "view"
  >;

  getDataset: TypedContractMethod<
    [_datasetId: string],
    [
      [string, bigint, boolean] & {
        owner_: string;
        pricePerUse_: bigint;
        exists_: boolean;
      }
    ],
    "view"
  >;

  getLicense: TypedContractMethod<
    [_licenseId: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        buyer_: string;
        agentId_: string;
        purchasedAt_: bigint;
        active_: boolean;
      }
    ],
    "view"
  >;

  hasLicense: TypedContractMethod<
    [_buyer: AddressLike, _agentId: string],
    [boolean],
    "view"
  >;

  isLicenseActive: TypedContractMethod<
    [_licenseId: BigNumberish],
    [boolean],
    "view"
  >;

  licenseExists: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  licenses: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        buyer: string;
        agentId: string;
        purchasedAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  nextLicenseId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformWallet: TypedContractMethod<[], [string], "view">;

  registerAgent: TypedContractMethod<
    [_agentId: string, _price: BigNumberish, _datasetId: string],
    [void],
    "nonpayable"
  >;

  registerDataset: TypedContractMethod<
    [_datasetId: string, _pricePerUse: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPlatformWallet: TypedContractMethod<
    [_wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, boolean] & {
        creator: string;
        datasetId: string;
        price: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "buyLicense"
  ): TypedContractMethod<[_agentId: string], [void], "payable">;
  getFunction(
    nameOrSignature: "datasets"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, bigint, boolean] & {
        owner: string;
        pricePerUse: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [_agentId: string],
    [
      [string, string, bigint, boolean] & {
        creator_: string;
        datasetId_: string;
        price_: bigint;
        exists_: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDataset"
  ): TypedContractMethod<
    [_datasetId: string],
    [
      [string, bigint, boolean] & {
        owner_: string;
        pricePerUse_: bigint;
        exists_: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLicense"
  ): TypedContractMethod<
    [_licenseId: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        buyer_: string;
        agentId_: string;
        purchasedAt_: bigint;
        active_: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasLicense"
  ): TypedContractMethod<
    [_buyer: AddressLike, _agentId: string],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isLicenseActive"
  ): TypedContractMethod<[_licenseId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "licenseExists"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "licenses"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        buyer: string;
        agentId: string;
        purchasedAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextLicenseId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [_agentId: string, _price: BigNumberish, _datasetId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerDataset"
  ): TypedContractMethod<
    [_datasetId: string, _pricePerUse: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformWallet"
  ): TypedContractMethod<[_wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "DatasetRegistered"
  ): TypedContractEvent<
    DatasetRegisteredEvent.InputTuple,
    DatasetRegisteredEvent.OutputTuple,
    DatasetRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "LicensePurchased"
  ): TypedContractEvent<
    LicensePurchasedEvent.InputTuple,
    LicensePurchasedEvent.OutputTuple,
    LicensePurchasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlatformWalletUpdated"
  ): TypedContractEvent<
    PlatformWalletUpdatedEvent.InputTuple,
    PlatformWalletUpdatedEvent.OutputTuple,
    PlatformWalletUpdatedEvent.OutputObject
  >;

  filters: {
    "AgentRegistered(string,address,uint256,string)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "DatasetRegistered(string,address,uint256)": TypedContractEvent<
      DatasetRegisteredEvent.InputTuple,
      DatasetRegisteredEvent.OutputTuple,
      DatasetRegisteredEvent.OutputObject
    >;
    DatasetRegistered: TypedContractEvent<
      DatasetRegisteredEvent.InputTuple,
      DatasetRegisteredEvent.OutputTuple,
      DatasetRegisteredEvent.OutputObject
    >;

    "LicensePurchased(uint256,string,address,uint256,address,address)": TypedContractEvent<
      LicensePurchasedEvent.InputTuple,
      LicensePurchasedEvent.OutputTuple,
      LicensePurchasedEvent.OutputObject
    >;
    LicensePurchased: TypedContractEvent<
      LicensePurchasedEvent.InputTuple,
      LicensePurchasedEvent.OutputTuple,
      LicensePurchasedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlatformWalletUpdated(address)": TypedContractEvent<
      PlatformWalletUpdatedEvent.InputTuple,
      PlatformWalletUpdatedEvent.OutputTuple,
      PlatformWalletUpdatedEvent.OutputObject
    >;
    PlatformWalletUpdated: TypedContractEvent<
      PlatformWalletUpdatedEvent.InputTuple,
      PlatformWalletUpdatedEvent.OutputTuple,
      PlatformWalletUpdatedEvent.OutputObject
    >;
  };
}
