/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BaserootMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentCount"
      | "agents"
      | "datasets"
      | "owner"
      | "pay"
      | "payForService"
      | "platformFeePercent"
      | "registerAgent"
      | "registerDataset"
      | "renounceOwnership"
      | "setPlatformFee"
      | "transferOwnership"
      | "updateAgent"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRegistered"
      | "AgentUpdated"
      | "DatasetRegistered"
      | "OwnershipTransferred"
      | "PlatformFeeUpdated"
      | "ServicePaid"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "agents", values: [string]): string;
  encodeFunctionData(functionFragment: "datasets", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pay",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "payForService",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string, BigNumberish, string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "registerDataset",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAgent",
    values: [string, BigNumberish, string, boolean]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(functionFragment: "agentCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "datasets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payForService",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerDataset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agentId: string,
    creator: AddressLike,
    price: BigNumberish,
    metadata: string
  ];
  export type OutputTuple = [
    agentId: string,
    creator: string,
    price: bigint,
    metadata: string
  ];
  export interface OutputObject {
    agentId: string;
    creator: string;
    price: bigint;
    metadata: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentUpdatedEvent {
  export type InputTuple = [
    agentId: string,
    price: BigNumberish,
    metadata: string,
    isActive: boolean
  ];
  export type OutputTuple = [
    agentId: string,
    price: bigint,
    metadata: string,
    isActive: boolean
  ];
  export interface OutputObject {
    agentId: string;
    price: bigint;
    metadata: string;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DatasetRegisteredEvent {
  export type InputTuple = [
    datasetId: string,
    provider: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [
    datasetId: string,
    provider: string,
    price: bigint
  ];
  export interface OutputObject {
    datasetId: string;
    provider: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [newFeePercent: BigNumberish];
  export type OutputTuple = [newFeePercent: bigint];
  export interface OutputObject {
    newFeePercent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServicePaidEvent {
  export type InputTuple = [
    agentId: string,
    user: AddressLike,
    amount: BigNumberish,
    creditId: BigNumberish
  ];
  export type OutputTuple = [
    agentId: string,
    user: string,
    amount: bigint,
    creditId: bigint
  ];
  export interface OutputObject {
    agentId: string;
    user: string;
    amount: bigint;
    creditId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BaserootMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): BaserootMarketplace;
  waitForDeployment(): Promise<this>;

  interface: BaserootMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentCount: TypedContractMethod<[], [bigint], "view">;

  agents: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, string, boolean] & {
        id: string;
        creator: string;
        price: bigint;
        metadata: string;
        isActive: boolean;
      }
    ],
    "view"
  >;

  datasets: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, boolean] & {
        id: string;
        provider: string;
        pricePerUse: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pay: TypedContractMethod<
    [_agentId: string, _creator: AddressLike],
    [void],
    "payable"
  >;

  payForService: TypedContractMethod<[_agentId: string], [void], "payable">;

  platformFeePercent: TypedContractMethod<[], [bigint], "view">;

  registerAgent: TypedContractMethod<
    [
      _agentId: string,
      _price: BigNumberish,
      _metadata: string,
      _datasetIds: string[]
    ],
    [void],
    "nonpayable"
  >;

  registerDataset: TypedContractMethod<
    [_datasetId: string, _pricePerUse: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPlatformFee: TypedContractMethod<
    [_percent: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateAgent: TypedContractMethod<
    [
      _agentId: string,
      _price: BigNumberish,
      _metadata: string,
      _isActive: boolean
    ],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, string, boolean] & {
        id: string;
        creator: string;
        price: bigint;
        metadata: string;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "datasets"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, boolean] & {
        id: string;
        provider: string;
        pricePerUse: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pay"
  ): TypedContractMethod<
    [_agentId: string, _creator: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "payForService"
  ): TypedContractMethod<[_agentId: string], [void], "payable">;
  getFunction(
    nameOrSignature: "platformFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [
      _agentId: string,
      _price: BigNumberish,
      _metadata: string,
      _datasetIds: string[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerDataset"
  ): TypedContractMethod<
    [_datasetId: string, _pricePerUse: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[_percent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAgent"
  ): TypedContractMethod<
    [
      _agentId: string,
      _price: BigNumberish,
      _metadata: string,
      _isActive: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentUpdated"
  ): TypedContractEvent<
    AgentUpdatedEvent.InputTuple,
    AgentUpdatedEvent.OutputTuple,
    AgentUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DatasetRegistered"
  ): TypedContractEvent<
    DatasetRegisteredEvent.InputTuple,
    DatasetRegisteredEvent.OutputTuple,
    DatasetRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeUpdated"
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ServicePaid"
  ): TypedContractEvent<
    ServicePaidEvent.InputTuple,
    ServicePaidEvent.OutputTuple,
    ServicePaidEvent.OutputObject
  >;

  filters: {
    "AgentRegistered(string,address,uint256,string)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentUpdated(string,uint256,string,bool)": TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;
    AgentUpdated: TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;

    "DatasetRegistered(string,address,uint256)": TypedContractEvent<
      DatasetRegisteredEvent.InputTuple,
      DatasetRegisteredEvent.OutputTuple,
      DatasetRegisteredEvent.OutputObject
    >;
    DatasetRegistered: TypedContractEvent<
      DatasetRegisteredEvent.InputTuple,
      DatasetRegisteredEvent.OutputTuple,
      DatasetRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlatformFeeUpdated(uint256)": TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;

    "ServicePaid(string,address,uint256,uint256)": TypedContractEvent<
      ServicePaidEvent.InputTuple,
      ServicePaidEvent.OutputTuple,
      ServicePaidEvent.OutputObject
    >;
    ServicePaid: TypedContractEvent<
      ServicePaidEvent.InputTuple,
      ServicePaidEvent.OutputTuple,
      ServicePaidEvent.OutputObject
    >;
  };
}
