/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BaserootMarketplace } from "./BaserootMarketplace";
export type { BaserootMarketplaceV2 } from "./BaserootMarketplaceV2";
